### ISSUE TITLE
ModuleNotFoundError: No module named 'pyaqsapi.helperfunctions'

### ISSUE THREAD

**Issue by CatcherGG** [USEPA/pyaqsapi#16]
After installing and following all the steps explained in the readme, I see the following error:
```python
ModuleNotFoundError: No module named 'pyaqsapi.helperfunctions'
```
Any ideas?

**Comment by mccroweyclinton-EPA** [comment]
Good afternoon, do you know which commit you are using. I pushed some changes to the code in the past few days that address import issues that were present in the code. This may fix the problem. Let me know if this does not.

**Comment by mccroweyclinton-EPA** [comment]
closed due to no response in 2 weeks. If you have further issues, please start a new discussion.

**Comment by mccroweyclinton-EPA** [comment]
closed
